=== NoahGlezRguez/lenguajeDeMarcas/XML/ejercicioXMLSchema_Noah/ej14/schemaEjercicio14Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:simpleType name="formatoMatricula">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{4}-[B-DF-HJ-NPR-TV-Z]{3}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="formatoDNI">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{8}[A-Z-[IOU]]"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="formatoNIE">
		<xs:restriction base="xs:string">
			<xs:pattern value="(X|Y|Z)[0-9]{7}[A-Z-[IOU]]"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="datos">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="perfil">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="matricula" type="formatoMatricula"/>
							<xs:choice>
								<xs:element name="DNI" type="formatoDNI"/>
								<xs:element name="NIE" type="formatoNIE"/>
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NoahGlezRguez/lenguajeDeMarcas/XML/ejercicioXMLSchema_Noah/ej14/ej14.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="schemaEjercicio14Schema.xsd">
	<perfil>
		<matricula>1234-BDC</matricula>
		<DNI>65498721G</DNI>
	</perfil>
	<perfil>
		<matricula>7894-GGG</matricula>
		<NIE>X7897894D</NIE>
	</perfil>
	<perfil>
		<matricula>3216-MSD</matricula>
		<DNI>14513455K</DNI>
	</perfil>
</datos>
