=== NoahGlezRguez/lenguajeDeMarcas/XML/ejercicioXMLSchema_Noah/ej7/schemaEjercicio7Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="TipoDireccion">
		<xs:sequence>

			<xs:element name="calle">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="numero">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="1000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			
			<xs:element name="ciudad" type="texto50char"/>

			<xs:element name="provincia" type="texto50char"/>	

		</xs:sequence>
	</xs:complexType>	

	<xs:simpleType name="texto50char">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="formatoTelefonico">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="formatoDni">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{8}[A-Z]"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="alumnos">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="alumno" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>

							<xs:element name="nombre" type="xs:string"/>

							<xs:element name="direccion" type="TipoDireccion"/>

							<xs:choice>
								<xs:element name="telefono" minOccurs="1" maxOccurs="1" type="formatoTelefonico"/>
								<xs:element name="movil" minOccurs="1" maxOccurs="3" type="formatoTelefonico"/>
							</xs:choice>

							<xs:element name="email" type="xs:string"/>
							
						</xs:sequence>

						<xs:attribute name="dni" type="xs:string" use="required"/>
						<xs:attribute name="repetidor" type="xs:boolean" default="false"/>
						<xs:attribute name="fechaNacimiento" type="xs:date" use="required"/>

					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== NoahGlezRguez/lenguajeDeMarcas/XML/ejercicioXMLSchema_Noah/ej7/ej7.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schemaEjercicio7Schema.xsd">
	<alumno dni="45645645H" repetidor="true" fechaNacimiento="1994-06-12">
		<nombre>Iraide Etxeberria</nombre>
		<direccion>
			<calle>Kalenagusia</calle>
			<numero>5</numero>
			<ciudad>Bilbao</ciudad>
			<provincia>Bizkaia</provincia>
		</direccion>
		<telefono>944000000</telefono>
		<email>ertset</email>
	</alumno>
	<alumno dni="12345678G" fechaNacimiento="1996-09-30">
		<nombre>Joseba Mikel Zarraga</nombre>
		<direccion>
			<calle>Gorbeia</calle>
			<numero>75</numero>
			<ciudad>Artea</ciudad>
			<provincia>Bizkaia</provincia>
		</direccion>
		<movil>622999999</movil>
		<movil>722456789</movil>
		<email>ertsert</email>
	</alumno>
</alumnos>
