=== NoahGlezRguez/lenguajeDeMarcas/XPath/ejercicioExpresionesAnidadas/centros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="centros">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="centro" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"></xs:element>
							<xs:element name="web" type="xs:string"></xs:element>
							<xs:element name="ciclos">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="ciclo">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre" type="xs:string"></xs:element>
													<xs:element name="grado" type="xs:string"></xs:element>
													<xs:element name="decretoTitulo">
														<xs:complexType>
															<xs:attribute name="anio" type="xs:gYear"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:string"></xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>	
								</xs:complexType>
							</xs:element>
							<xs:element name="modulos">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="modulo">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre"></xs:element>
													<xs:element name="curso"></xs:element>
													<xs:element name="horasSemanales"></xs:element>
													<xs:sequence maxOccurs="unbounded">
														<xs:element name="ciclo" type="xs:string"></xs:element>
													</xs:sequence>
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer"></xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NoahGlezRguez/lenguajeDeMarcas/XPath/ejercicioExpresionesAnidadas/centros.xml
<?xml version="1.0" encoding="UTF-8"?>
<centros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="centros.xsd">
	<centro>
		<nombre>Elorrieta</nombre>
		<web>https://elorrieta.hezkuntza.net/es/inicio</web>
		<ciclos>
			<ciclo id="ASIR">
				<nombre>Administración de Sistemas Informáticos en Red</nombre>
				<grado>Superior</grado>
				<decretoTitulo anio="2009" />
			</ciclo>
			<ciclo id="DAW">
				<nombre>Desarrollo de Aplicaciones Web</nombre>
				<grado>Superior</grado>
				<decretoTitulo anio="2010" />
			</ciclo>
			<ciclo id="SMR">
				<nombre>Sistemas Microinformáticos y Redes</nombre>
				<grado>Medio</grado>
				<decretoTitulo anio="2008" />
			</ciclo>
		</ciclos>
		<modulos>
			<modulo id="0228">
				<nombre>Aplicaciones web</nombre>
				<curso>2</curso>
				<horasSemanales>4</horasSemanales>
				<ciclo>SMR</ciclo>
			</modulo>
			<modulo id="0372">
				<nombre>Gestión de bases de datos</nombre>
				<curso>1</curso>
				<horasSemanales>5</horasSemanales>
				<ciclo>ASIR</ciclo>
			</modulo>
			<modulo id="0373">
				<nombre>Lenguajes de marcas y sistemas de gestión de información</nombre>
				<curso>1</curso>
				<horasSemanales>3</horasSemanales>
				<ciclo>ASIR</ciclo>
				<ciclo>DAW</ciclo>
			</modulo>
			<modulo id="0376">
				<nombre>Implantación de aplicaciones web</nombre>
				<curso>2</curso>
				<horasSemanales>5</horasSemanales>
				<ciclo>ASIR</ciclo>
			</modulo>
		</modulos>
	</centro>
</centros>
