=== NoahGlezRguez/lenguajeDeMarcas/practicasParaExamen3ªEval/ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="TextoConUnidad">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="unidad" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MemoriaRAM">
    <xs:simpleContent>
      <xs:restriction base="TextoConUnidad">
        <xs:minInclusive value="8"/>
        <xs:maxInclusive value="1024"/>
        <xs:attribute name="unidad" type="xs:string" fixed="GB" use="required"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="datacenter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="servidor" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hostname">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="srv-[a-z]{3}-\d{2}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:choice>
                <xs:element name="ip_v4" type="xs:string"/>
                <xs:element name="ip_v6" type="xs:string"/>
              </xs:choice>
              <xs:element name="ram" type="MemoriaRAM"/>
            </xs:sequence>
            <xs:attribute name="rol" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="BBDD"/>
                  <xs:enumeration value="Web"/>
                  <xs:enumeration value="Backend"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NoahGlezRguez/lenguajeDeMarcas/practicasParaExamen3ªEval/ej1_respuesta.xml
<?xml version="1.0" encoding="UTF-8"?>
<datacenter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="ej1.xsd">
		
	<servidor rol="BBDD">
		<hostname>srv-qwe-23</hostname>
		<ip_v4>123.32.4.15</ip_v4>
		<ram unidad="GB">16</ram>
	</servidor>
	<servidor rol="Web">
		<hostname>srv-gfd-78</hostname>
		<ip_v6>255.76.466.2</ip_v6>
		<ram unidad="GB">64</ram>
	</servidor>
	<servidor rol="Backend">
		<hostname>srv-odh-21</hostname>
		<ip_v4>144.633.53.34</ip_v4>
		<ram unidad="GB">256</ram>
	</servidor>

</datacenter>
